### PR TITLE
Elude the JSON mapper dependency (part of #76)

### PR DESCRIPTION
**Pull request by marksto**
Here's the JSON mapping part of the deal.

### CODE REVIEW

**Comment by marksto** [comment]
Server-side tests run smoothly.

Also, you may check that some lib is required at CP, e.g. by firing the `lein test`. It'll rise the following exception:
```
No supported JSON mapper library supplied. Consider adding one of the ["cheshire"], ["metosin/jsonista"], ["org.clojure/data.json"] to the project deps.
```

The supported JSON mapper libs are ordered according to their popularity.

**Comment by marksto** [comment]
Bill, are you good with this design?
And could you, please, double-check that no extra dependencies (logging, mapping) make their way into the release artifact.

**Review by wdhowe — COMMENTED** [review]
This looks good overall.

What do you think about these modifications?

In the json ns:
- Please add docstrings to all functions.
- Remove the "json" from functions/var names. It feels redundant to me in the json ns.
  - example: json/parse-str instead of json/parse-json-str

**Comment by wdhowe** [comment]
> Bill, are you good with this design?
> And could you, please, double-check that no extra dependencies (logging, mapping) make their way into the release artifact.

It looks like none of the pulled out extras are included in the standalone jar:

- Cloned your branch
- Built an uberjar
- Inspected with jar:

```bash
# no results for any json libs
> $ jar tf telegrambot-lib-0.3.5-standalone.jar | grep cheshire

> $ jar tf telegrambot-lib-0.3.5-standalone.jar | grep jsonista

> $ jar tf telegrambot-lib-0.3.5-standalone.jar | grep data.json

# left as is clj-http has results as expected
> $ jar tf telegrambot-lib-0.3.5-standalone.jar | grep clj-http
META-INF/maven/clj-http/clj-http/pom.xml
META-INF/leiningen/clj-http/clj-http/project.clj
META-INF/leiningen/clj-http/clj-http/README.org
META-INF/leiningen/clj-http/clj-http/LICENSE
META-INF/maven/clj-http/
META-INF/maven/clj-http/clj-http/
META-INF/maven/clj-http/clj-http/pom.properties
```

**Comment by marksto** [comment]
Thanks for the feedback!

I decided to leave only 2 fns with `json-str` in their names, but a) they are `:private`, and b) their names are too short and too general w/o these prefixes (`parser` and `generator`, namely). Everything else now has shorter and clearer names and docstrings.

I also decided to add some extra safety checks here and there, after taking a look on this code for a second time.

**Comment by marksto** [comment]
> It looks like none of the pulled out extras are included in the standalone jar

Well, somehow I was able to find the `logback` dependencies in my local installation. And fixed this with `lein clean`, then `lein with-profiles prod install`. Anyway, I'm mostly concered about the `dev` deps in _the release_ uberjar. Let's just triple-check during the `1.0.0` release.

**Comment by wdhowe** [comment]
> > It looks like none of the pulled out extras are included in the standalone jar
> 
> Well, somehow I was able to find the `logback` dependencies in my local installation. And fixed this with `lein clean`, then `lein with-profiles prod install`. Anyway, I'm mostly concered about the `dev` deps in the _release_ uberjar. Let's just triple-check during the `1.0.0` release. eyes

Ah, I didn't check for logback before.

I'm good with merging this if you are ready.

**Comment by marksto** [comment]
Yes, please. Let's merge this PR.

P.S. Thank you for updating the #74. I myself would like to address all documentation-related issues within one task.

**Pull request merged**
